<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Providers Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }
        .stat-item {
            text-align: center;
        }
        .stat-number {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .status-inactive {
            color: #dc3545;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title ?? 'Providers Report' }}</h1>
        <p>Generated on {{ $generated_at }}</p>
    </div>

    @if(isset($stats))
    <div class="stats">
        <div class="stat-item">
            <div class="stat-number">{{ $stats['total_count'] }}</div>
            <div class="stat-label">Total Providers</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['active_count'] }}</div>
            <div class="stat-label">Active</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['inactive_count'] }}</div>
            <div class="stat-label">Inactive</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $stats['specialties_count'] }}</div>
            <div class="stat-label">Specialties</div>
        </div>
        @if($stats['average_rate'])
        <div class="stat-item">
            <div class="stat-number">${{ number_format($stats['average_rate'], 2) }}</div>
            <div class="stat-label">Avg. Rate</div>
        </div>
        @endif
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Specialty</th>
                <th>Rate</th>
                <th>Status</th>
                <th>Appointments</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($providers as $provider)
            <tr>
                <td>{{ $provider->id }}</td>
                <td>{{ $provider->user->name ?? 'N/A' }}</td>
                <td>{{ $provider->user->email ?? 'N/A' }}</td>
                <td>{{ $provider->specialty }}</td>
                <td>
                    @if($provider->hourly_rate)
                        ${{ number_format($provider->hourly_rate, 2) }}
                    @else
                        Not set
                    @endif
                </td>
                <td class="{{ $provider->is_active ? 'status-active' : 'status-inactive' }}">
                    {{ $provider->is_active ? 'Active' : 'Inactive' }}
                </td>
                <td>{{ $provider->appointments->count() }}</td>
                <td>{{ $provider->created_at->format('M j, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report contains {{ $providers->count() }} provider(s) | Generated by Healthcare Management System</p>
    </div>
</body>
</html>